# Generated by Django 4.1.2 on 2022-10-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Municipio", models.CharField(max_length=30)),
                ("TN", models.CharField(max_length=20)),
                ("Numero", models.CharField(max_length=20)),
                ("Descricao", models.CharField(max_length=140, null=True)),
                ("Unidade", models.CharField(max_length=20, null=True)),
                ("Prazo", models.DateField(null=True)),
                (
                    "Situacao",
                    models.CharField(
                        choices=[("A", "Atendida"), ("P", "Pendente")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("OBS", models.CharField(max_length=40, null=True)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
            ],
            options={"verbose_name_plural": "NC",},
        ),
    ]
