# Generated by Django 4.1.2 on 2022-10-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ncs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nc",
            name="Descricao",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="nc", name="Municipio", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="nc",
            name="Unidade",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
