# Generated by Django 4.1.2 on 2022-10-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ncs", "0005_alter_nc_situacao"),
    ]

    operations = [
        migrations.RenameModel(old_name="NC", new_name="Nao_Conformidades",),
    ]
