# Generated by Django 4.1.2 on 2022-10-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ncs", "0006_rename_nc_nao_conformidades"),
    ]

    operations = [
        migrations.RenameModel(old_name="Nao_Conformidades", new_name="NC",),
    ]
