# Generated by Django 4.1.2 on 2022-10-27 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaSAA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta", models.CharField(max_length=500)),
                ("Prazo", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MetaSES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta", models.CharField(max_length=500)),
                ("Prazo", models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="municipio",
            name="instrumento_contratual",
            field=models.CharField(
                choices=[
                    ("Contrato de Programa", "Contrato de Programa"),
                    ("Contrato de Concessão", "Contrato de Concessão"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.DeleteModel(name="Metas",),
        migrations.AddField(
            model_name="metases",
            name="municipio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contratos.municipio",
            ),
        ),
        migrations.AddField(
            model_name="metasaa",
            name="municipio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contratos.municipio",
            ),
        ),
    ]
